### ISSUE TITLE
Berlin CityGML refuses to work

### ISSUE THREAD

**Issue by kekscom** [polygon-city/citygml-to-obj#1]
I've tried district "Mitte":

Fix orientation for polygons: [ 1, 2 ]
Fix orientation for polygons: [ 0, 1, 2, 5, 6, 7, 8, 9, 10, 11, 12 ]

citygml-obj/node_modules/triangulate/node_modules/poly2tri/src/sweepcontext.js:67
            throw new PointError('poly2tri Invalid Edge constructor: repeated 
                  ^
Error
    at Object.<anonymous> (citygml-obj/node_modules/triangulate/node_modules/poly2tri/src/pointerror.js:48:24)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (citygml-obj/node_modules/triangulate/node_modules/poly2tri/src/poly2tri.js:81:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by robhawkes** [comment]
Thanks for reporting this! Looks like I need to add some more repairs for the simpler geometry errors (such as repeated vertices like in this case). I'll make this a priority.

**Comment by robhawkes** [comment]
For my own reference, it's likely I'll benefit from the `dedupe` and `clean` methods in Polygon.js

**Comment by robhawkes** [comment]
I've pushed an update (0.1.5) that uses a new triangulation library. Can you see if you see the same issue?

**Comment by kekscom** [comment]
It ran a lot further!
But..

root: 
   { trap: null,
     yval: { id: 6, x: 21.998101851103492, y: 0.00720784133233221 },
     right: { trap: null, yval: [Object], right: [Object], left: [Object] },
     left: { trap: null, yval: [Object], right: [Object], left: [Object] } } }
citygml-obj/node_modules/triangulate/node_modules/pnltri/pnltri.js:395
            while ( frontPt = frontMono.vFrom ) {               // assignment !
                                       ^
TypeError: Cannot read property 'vFrom' of null
    at find_monotone_chain_max (citygml-obj/node_modules/triangulate/node_modules/pnltri/pnltri.js:395:31)
    at PNLTRI.PolygonData.unique_monotone_chains_max (citygml-obj/node_modules/triangulate/node_modules/pnltri/pnltri.js:423:17)
    at PNLTRI.MonoSplitter.monotonate_trapezoids (citygml-obj/node_modules/triangulate/node_modules/pnltri/pnltri.js:1871:17)
    at PNLTRI.Triangulator.triangulate_polygon (citygml-obj/node_modules/triangulate/node_modules/pnltri/pnltri.js:2086:19)
    at triangulatePnlTri (citygml-obj/node_modules/triangulate/index.js:25:28)
    at citygml-obj/index.js:134:21
    at arrayEach (citygml-obj/node_modules/lodash/index.js:1314:13)
    at Function.<anonymous> (citygml-obj/node_modules/lodash/index.js:3355:13)
    at citygml-obj/index.js:132:9
    at fn (citygml-obj/node_modules/async/lib/async.js:712:34)

**Comment by robhawkes** [comment]
Blast! Well I think this is a separate issue as I ran into this too with a large dataset – if I output the OBJ as a string and not as a file then this error doesn't occur. Hmm.

**Comment by robhawkes** [comment]
Could you humour me and see if the same error occurs under the following circumstances (highlighted the one I think is causing it):
1. With the terminal minimised while you run the script
2. **With the "Fix orientation…" logging removed (I just pushed a new version)**
3. When run a few times
4. When run with a fresh directory (eg. all the previous OBJ files deleted)

Mine isn't outputting that error for me any more and I'm trying to work out why (nothing has changed in the code).

_Edit: Mine is outputting the error but only when I have the terminal window (and logging) active while it's running. Bizarre!_

**Comment by kekscom** [comment]
Got event more resulting objects but at some point same thing happens. I'll try again with very latest data and suggest you do as well: ftp://download-berlin3d.virtualcitymap.de/citygml/ using "Mitte"

**Comment by robhawkes** [comment]
I've unfortunately got a very bad Internet connection but I'll see what I can do with the Berlin data I already have available.

**Comment by kekscom** [comment]
Ok, the most recent version of Mitte has 500 MB less than my old one. Whatever that means.
I've tried it and get the same thing, but a lot earlier.

> Cannot read property 'vFrom' of null

**Comment by robhawkes** [comment]
Ok thanks, I'll see what exactly is causing this and post an update here.

**Comment by robhawkes** [comment]
I've pushed some updates that have dramatically improved both the output quality and speed. I've tested this on a subset of the Mitte dataset and it's working great – the script doesn't error out in the same way as before.

It's possible that some buildings may not look valid, though this down to a geometry error rather than an error with the OBJ creation. I'm debating skipping the conversion of buildings that fail validation checks and which cannot be repaired, but for now I output everything that can be triangulated.

How are things for you with the latest version (0.1.9)?

**Comment by kekscom** [comment]
Better again.
Didn't check any geometry at all so far but will when conversion runs through.
What I got:
Saved: out/DEB_LOD2_UUID_8bf7884d-b01c-48da-a9a2-ebca7648c347.obj
citygml-obj/node_modules/citygml-validate-shell/index.js:466
    var checkPoints2d = points3dto2d(outerPolygon[0], false);
                                                 ^
TypeError: Cannot read property '0' of undefined
    at citygml-obj/node_modules/citygml-validate-shell/index.js:466:50
    at citygml-obj/node_modules/async/lib/async.js:699:13
    at iterate (citygml-obj/node_modules/async/lib/async.js:256:13)
    at process._tickCallback (node.js:355:11)

**Comment by robhawkes** [comment]
That's good to hear things are better. The new error looks simple enough to handle – seems to be an issue where some of the Berlin buildings are missing / complete invalid (eg. most / all of the DEB_ ones). I'll add in some checks to avoid and notify on those errors rather than crashing out.

**Comment by robhawkes** [comment]
I've pushed an update that should report but not crash on completely broken geometry like the one you encountered earlier. Let me know if it has helped.

In the meantime, I'll continue to download the entire Mitte dataset so I can use that for testing.

**Comment by kekscom** [comment]
From what I tested, there are no errors anymore. Can't tell whether just not thrown, but fine that way.
I had to stop the process after 1.5h for Mitte. It kept converting but that's just too long for now.

**Comment by robhawkes** [comment]
Cool ok, that's partly good news then. I'm currently working on a few things that'll dramatically speed up the processing time (using multiple threads, micro-optimisations, etc) and I'll update the package when it's done. I've just finished downloading the full Mitte dataset so I'll be able to use that for testing from now on.

**Comment by robhawkes** [comment]
I've pushed 0.1.13 which adds early multi-threaded processing support. I'm able to convert the entire 900MB Mitte in about 16 minutes using my 16 CPU cores. Mileage will vary depending on how many CPUs you have but it should be _a lot_ faster now. Let me know how you get on.

**Comment by robhawkes** [comment]
I'm going to close this under the assumption that things are a lot better now – we've been using the Mitte.gml file ourselves and have been able to convert it within a reasonable amount of time (which could be improved further with tweaks to the validation steps).

Let me know if this isn't the case and we can reopen it.

**Comment by meetar** [comment]
Looking great! Converted 19257 buildings from Mitte.gml in 13 minutes here, though the gml file has 19296 bldg:Building objects, with no anomalies reported in the output – any idea what could account for the discrepancy?

**Comment by robhawkes** [comment]
Realised I didn't reply to this! I imagine the discrepancy in total buildings output was related to #10 and should have been fixed a while ago now. Let me know if this isn't the case.
