### ISSUE TITLE
Abide by Valhalla rate limits

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/citygml-to-obj#12]
CityGML files that are missing `GroundSurface` elements will cause a call to Valhalla for every building – this quickly triggers rate limiting from Valhalla and causes the buildings not to be converted.

Some kind of approach needs to be implemented to work around this, either:
- A simple queue that we know keeps the number of concurrent requests below the rate limit
- An advanced approach that listens to the rate limit messages and works out what to do (eg. holds back failed requests for some period of time)

**Comment by robhawkes** [comment]
@meetar Is is possible to get a Valhalla key with increased limits? The current limit of 2 per second is proving a bit of a pain and a bottleneck for efficient CityGML conversion.

**Comment by meetar** [comment]
Done!
