### ISSUE TITLE
Collinear error

### ISSUE THREAD

**Issue by moklick** [polygon-city/citygml-to-obj#2]
Hey @robhawkes 

when I try to convert a citygml-file from http://www.citygml.org/?id=1539 I get the following error:

/triangulate/node_modules/poly2tri/src/sweep.js:152
`throw new PointError('poly2tri EdgeEvent: Collinear not supported!'`

Are not all citygml files supported?

**Comment by moklick** [comment]
I am closing this issue, because there is already one with the same error

**Comment by robhawkes** [comment]
Thanks for reporting! As with #1, there are a bunch of simple geometry repairs that we should do to avoid colinear and other basic vertex errors. I'll make this a priority.

I've tested successfully on a lot of CityGML 1.0 and 2.0, though it's errors and examples like this that will allow us to support everything (where possible).

**Comment by kekscom** [comment]
:+1:

**Comment by robhawkes** [comment]
I'll re-open for now as this is a different validation error and so will likely require separate work.

**Comment by robhawkes** [comment]
For the record, these validation errors should be successfully reported by [citygml-validate-file](https://github.com/polygon-city/citygml-validate-file), we just don't repair anything other than normals right now.

**Comment by moklick** [comment]
Ok! Thanks for the fast reply :+1:

**Comment by robhawkes** [comment]
I've pushed an update (0.1.5) that uses a new triangulation library. Can you see if you see the same issue?

**Comment by moklick** [comment]
Seems to work now! Thanks. 
I will check some more files.

**Comment by robhawkes** [comment]
Awesome! Let me know how you get on.

**Comment by robhawkes** [comment]
I've pushed a few more updates that should improve things further. I'm going to close this under the assumption that everything is fixed, but please re-open should it not be.
