### ISSUE TITLE
Unable to retrieve elevation data

### ISSUE THREAD

**Issue by meetar** [polygon-city/citygml-to-obj#4]
Getting this error:

```
Unable to retrieve elevation data
```

Which leads to "unable to convert building"

Unsure if this is Bing rate limits – their docs suggest it shouldn't be happening, although it may be throttled due to high demand.

Is there any way to catch this kind of error more specifically?

**Comment by meetar** [comment]
Interestingly, this problem went away after I threw away the buildings I'd already converted and started over from scratch. Could be a coincidence.

**Comment by meetar** [comment]
so once I've re-started a conversion after an out-of-memory error I always see this error eventually – but one interesting thing I've found is that I'll start seeing things like this:

```
Building has already been converted: output/DEB_LOD2_UUID_8bf7884d-b01c-48da-a9a2-ebca7648c347.obj
Unable to convert building: BLDG_0003000f00040f85
Unable to retrieve elevation data
Building has already been converted: output/BLDG_0003000e009a3895.obj
```

So in this case, BLDG_0003000f00040f85 is a previously-existing building – and then these apparent false hits become more common, until every building is reported this way, until (as far as I can tell from my tests) the last existing building is reached – but then the errors continue, naming non-existing buildings, until an out-of-memory error.

**Comment by meetar** [comment]
Here's a typical log:
https://gist.github.com/meetar/629d8caa286b9d1ef3b0

**Comment by meetar** [comment]
So it turns out the whole log didn't paste in there, and I checked the original log file and found this:

<img width="2176" alt="screen shot 2015-07-16 at 4 55 54 pm" src="https://cloud.githubusercontent.com/assets/459970/8735021/bf08c26e-2bdb-11e5-880b-fc5ce0ad9b6f.png">

…possibly related

**Comment by robhawkes** [comment]
One thing that's certain is that I need to implement some more robust checks and behaviour when the elevation API isn't accessible (whether because of rate-limiting or whatever). That should solve the original issue here, though it doesn't solve the problem of where to get semi-accurate elevation data from…

I'm not sure about the other errors yet – they might be as a result of the elevation stuff, or something else entirely. I'll make the elevation behaviour more robust first and we can see how that changes things.

**Comment by robhawkes** [comment]
1a406f1d3c102073103df4d0b160bae3b35cd1ca moves to a key-less Google elevation API so that should avoid some issues. Let me know if there are more elevation-related errors and I can dig further.

**Comment by robhawkes** [comment]
After some more tests it looks like it's still easy to start getting rate-limit messages. It seems that you can only do 10 requests per second with the Google API.

I'm going to need to have a think about how best to approach this, as if we only do 10 requests a second then it'll take over 1m30s for every 1,000 buildings. It's possible to batch the elevation requests for multiple buildings, though that'll require quite significant changes to the architecture to be able to match up the elevation results with the worker processes responsible for each elevation request.

**Comment by meetar** [comment]
I'm less sure about the rate-limiting now, especially since the errors seem to go away when I restart the conversion from scratch – so Bing might be fine once the "out of memory" problem is resolved.

**Comment by robhawkes** [comment]
Perhaps. Moving to the Google API for now makes sense anyway as it doesn't have a hard usage cap over a month like the Bing one (unless we shell out for an extortionate plan).

I'm going to have a think about where the memory issues are and see what I can do.

**Comment by meetar** [comment]
So I'm told our elevation API is being tested in dev – it's based on SRTM with some other sources mixed in, but I don't know where or how. I presume there's one to cover the +60 lat range, but I don't know anything about the data quality – it probably hasn't been filtered for building heights, so there's likely some noise in the system in urban areas. I'll want to try it anyway, it will be a very common use case.

**Comment by meetar** [comment]
This was also just brought to my attention, I have to assume it won't work for our purposes but here it is for reference: http://www.liedman.net/elevation-service/

**Comment by robhawkes** [comment]
Hmm, I forgot that SRTM data is affected by buildings. Still, it may be good enough for first version that's not reliant on Google or Bing. I imagine the original heights within the CityGML data is based on accurate LIDAR data so we may still get floating buildings.

All this effort does make me wonder why the ground height isn't included in the CityGML data, or why the relative height to ground level isn't used. I'll see if my CityGML friends have any suggestions.

**Comment by meetar** [comment]
Seems to be running more smoothly now – but I certainly ran into elevation rate limits, it converted 2500 and is skipping the rest, with "Elevation values not present in API response" errors.

But no queue or memory errors (so far), so: progress! Assuming it skips the rest I'll retry the conversion later today.

**Comment by robhawkes** [comment]
That's good news then! The elevation errors will persist until we either use the new internal API or work on a way to batch and rate-limit requests to Google / Bing (a lot harder to implement).

**Comment by meetar** [comment]
Okay, let's leave this open for now and I'll update when we're ready to test the new API.

**Comment by meetar** [comment]
So this is interesting, and looks relatively simple:

> Im running an elevation lookup service using open terrain data(SRTM) and https://github.om/perliedman/elevation-service Script used for fetching DEMs is at https://gist.github.com/JesseCrocker/1275882b1a48756e19db i filled in missing areas with 3 arc second SRTM, which is not covered in that script.
> 
> The service currently runs on an AWS t2.micro instance with a 400gb ebs volume to store the data, and is capable of doing ~5k points/seconds, for around $30/month.

Feasibly we could do the same thing until the Routing team has their service up and running. cc @bcamper

**Comment by robhawkes** [comment]
Looks nice! I couldn't see any setup instructions so I assume there's some manual tweaking to get something like this up and running. Certainly an alternative option though!

I've pinged my CityGML contacts to see if I can get a better understanding on how height is used in CityGML and whether I've mis-understood something – it's entirely possible the data we need is hidden in the (hugely verbose) CityGML files somewhere and I just don't know what I'm looking for.

**Comment by robhawkes** [comment]
So it looks like elevation values in CityGML aren't expected to be relative to the ground and there doesn't seem to be any elements or properties to surface that data within the CityGML either. Saying that, there are a couple of leads that may prove useful for us.
- The `boundedBy` element for each building should include the lowest point for the building, however this may actually be below ground level (eg. the bottom of a basement)
- The `measuredHeight` attribute (if it exists) could be used to calculate the building offset from ground-level

All in all, the guidance and approach recommended is to poll an external elevation API for each building. This is what we're already doing and it's what they CityGML guys are doing too – not practical but we don't have much choice it seems, at least for now.

**Comment by robhawkes** [comment]
I've run some initial tests with the dev elevation API and it's certainly better from a rate-limiting standpoint. However, from the buildings I've checked there can be a difference in height between the Google Elevation API of up to 10 metres (eg. [run this Google result through the dev API](http://maps.google.com/maps/api/elevation/json?sensor=false&locations=52.51454097222985,13.392177593206027)) – possibly more (though some are ok – within a few metres). I imagine this is due to the low pixel density, or noise created by buildings / cities in SRTM data.

Overall, this means that buildings could be offset up to +/- 10 metres more than they should, resulting in buildings embedded into or floating above the ground – which is bad considering some buildings may be shorter than the margin of error (ie. they make themselves new lives as underground bunkers). It really comes down to what kind of accuracy we want, which I would argue needs to be high considering building elevation is incredibly important in defining how _real_ a city looks.

One potential approach would be to forgo rough elevation APIs entirely and work out the lowest point that would leave no gaps between the building and ground plane – a more advanced approach to simply snapping the lowest building point to the ground plane. It's entirely possible that the margin for error here is significantly lower than that of the various elevation APIs, potentially a couple metres or so with the average being less than a metre – due to the fact that the building vertical-axis values are derived from LIDAR and as such only accounts for what it can see above-ground anyway.

Either way, I'd be interested to run some tests here for comparison.

**Comment by robhawkes** [comment]
I've managed to find [Berln's 2 and 5-metre accuracy terrain data](http://www.stadtentwicklung.berlin.de/geoinformation/landesvermessung/atkis/de/dgm.shtml) (which is open licensed!) so I'm going to use that as part of the comparison process to compare the APIs / approaches.

**Comment by robhawkes** [comment]
Ok so I've done a quick comparison using the dev API (SRTM), Google API and the lidar data from Berlin.

Assuming the following point (sprawling but relative short building) @ [52.53444783854353, 13.37425159625227](http://www.openstreetmap.org/#map=16/52.5344/13.3742):

![](http://cl.ly/image/0R0J3M373B3F/Screen%20Shot%202015-08-03%20at%2014.10.16.png)
- Lidar: 33.5m
- Google: 34.3m
- Dev: 39m
- Lowest point recorded by CityGML (not necessarily the ground): 31m

And another point (large road intersection) @ [52.52363, 13.35689](http://www.openstreetmap.org/#map=16/52.5236/13.3569):
- Lidar: 34.4m
- Google: 35m
- Dev: 35m

[And another](http://www.openstreetmap.org/#map=16/52.53310/13.35766):
- Lidar: 36.5m
- Google: 37.7m
- Dev: 39m

All in all, the results all differ which is expected. I'm still none-the-wiser about which one would be most accurate, considering that for one building the lowest point is 31m and yet none of the elevation APIs return values below 33.5m. The highest point of the building should be correct though (as it's lidar), so my gut says that highest point minus lidar terrain value equals offset value to calculate origin point for ground level.

**Comment by meetar** [comment]
I was afraid of that – in that case I agree, working from the data we already have is more likely to result in "good-enough" data. Maybe we can work in some kind of weirdness-detection to look for cases where there are numerous z-values near the calculated ground plane.

**Comment by robhawkes** [comment]
I'll have a think about what an approach for that might look like and compare the results. I think that edge-cases might make it difficult (eg. a building with legs like the Eiffel Tower) but we'll see how it goes.

On the plus side, the dev API is great for fairly accurate (sparse) terrain and this general problem is only applicable when rendering onto a flat plane like in ViziCities or Tangram. If we rendered onto a 3D terrain then everything should look ok with the original elevation values in the CityGML.

**Comment by robhawkes** [comment]
c327dfab87458f848b7b48383c853cbbc4355864 (0.1.24) experiments with using the highest `groundSurface` element (if exists) as a crude way of finding the best guess of ground elevation while avoiding the most obvious gaps between the building and ground that we've seen in the past. This isn't perfect as `groundSurface` can be used to define any part of the building that touches the ground (eg. the bottom of a basement), though we may not notice anything too abnormal if the CityGML data is derived from above-ground lidar (ie. no subterranean `groundSurface` elements exist in the data).

Seeing as this is a general library, it will probably be a good idea to enable these various elevation approaches as a user-definable option – some people will be happy with using the lowest point, some with using the highest `groundSurface`, others will want to use an external API like Google.

**Comment by meetar** [comment]
Still seeing a discrepancy between the citygml building count and the converted building count – checking the conversion log I see that the converter is still occasionally returning things like:

```
Unable to convert building: UUID_060cce13-df69-4ecc-9bc9-836a9efbfa82 
[Error: Unable to retrieve elevation data: getaddrinfo ENOTFOUND valhalla-elevation-dev-1428989121.us-east-1.elb.amazonaws.com valhalla-elevation-dev-1428989121.us-east-1.elb.amazonaws.com:80]
```

It could be a rate limit, but these errors are quite rare (23 out of 19k)... regardless, the converter never queues those buildings back up, and just fails on them.

1) Do we still need Valhalla (or any elevation service) if we're using groundSurface?
2) Can we requeue the failed buildings?

**Comment by robhawkes** [comment]
The conversion process [should only be requesting elevation data from Valhalla if it can't work out a sane height from the CityGML data](https://github.com/polygon-city/citygml-to-obj/blob/master/worker.js#L264). The fact that this isn't happening is definitely odd as it implies that the building doesn't have a `bldg:GroundSurface` CityGML element, which would make it invalid.

However, the fallback is for exactly this situation and should work. I'll do the following things:
1. Update the Valhalla endpoint to whatever it is now
2. Look into why building `UUID_060cce13-df69-4ecc-9bc9-836a9efbfa82` doesn't report a ground surface in CityGML

**Comment by robhawkes** [comment]
I've pushed `0.1.27` which updates the Valhalla endpoint and will now work as a fallback for buildings without a `bldg:GroundSurface`. You'll need to add the `valhallaKey` option when starting up `citygml-to-obj` (it's in the readme).

**Comment by robhawkes** [comment]
After digging through the Mitte set I found building `UUID_060cce13-df69-4ecc-9bc9-836a9efbfa82` and it definitely doesn't have a `bldg:GroundSurface`, nor any `bldg:WallSurface` elements – in short, this means we can't easily work out what's the ground and what's a roof or a wall so there isn't much we can do, though it should still output a valid 3D object.

It looks like these buildings are the exception, so the fixed Valhalla fallback should handle them better now and the rest will be handled by the `bldg:GroundSurface` logic.

Let me know if you still see a disparity in the number of converted buildings.
